[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "sfogliatrice"
version = "0.6.0"
description = "Python bindings for sfogliatrice tessellation."
license = { text = "MIT" }
keywords = ["geo", "geojson", "tessellation", "satellite"]
classifiers = [
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "sfogliatrice"
