[package]
name = "sfogliatrice_wasm"
version = "0.5.0"
edition = "2024"
authors = ["Ronaldo Racum <ronaldo@racum.com>"]
license = "MIT"
description = "WebAssembly bindings for sfogliatrice tessellation."
repository = "https://github.com/racum/sfogliatrice"
readme = "../README.md"
keywords = ["geo", "geojson", "tessellation", "satellite"]
categories = ["science", "aerospace"]
homepage = "https://github.com/racum/sfogliatrice"

[lib]
name = "sfogliatrice"
crate-type = ["cdylib", "rlib"]

[dependencies]
sfogliatrice_lib = { path = "../sfogliatrice_lib", version = "0.5.0" }
wasm-bindgen = "0.2"
js-sys = "0.3"
serde_json = "1"
uuid = { version = "1", features = ["js"] }  # forces js RNG backend for geodesy's transitive uuid dep

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--all-features"]
